export const USER_MAPPING = {
  id: 'a',
  provider: 'b',
  discoverFrom: 'c',
  confirmed: 'd',
  blocked: 'e',
  gender: 'f',
  birthday: 'g',
  avatar: 'h',
  deviceToken: 'i',
  createdAt: 'j',
  updatedAt: 'k',
  firstName: 'l',
  lastName: 'm',
  phone: 'n',
  username: 'o',
  email: 'p',
  password: 'q',
  given_name: 'r',
  family_name: 's',
};
